[project]
name = "wordle-solver"
version = "0.1.0"
description = "Program that solves wordle"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "pytest>=8.3.5",
    "rich>=14.0.0",
]
